### ISSUE TITLE
Error in System-Log Unknown insert tag {{form_rawvalue_get::*}}

### ISSUE THREAD

**Issue by wschwaiger** [e-spin/form-scr-default-bundle#2]
I get an error in the system-log that the insert tag is unknown.

Unknown insert tag {{form_rawvalue_get::*}}

I am running the extension under Contao 4.9.13. It works in the end, but I am not comfortable having that error, because it can cause side effects eventually.

**Comment by zonky2** [comment]
Open an info entry (i) and see who is looking for the insert tag...

**Comment by wschwaiger** [comment]
![Bildschirmfoto 2021-05-10 um 11 11 23](https://user-images.githubusercontent.com/458603/117635925-9a719f80-b180-11eb-808d-8e04a960c768.png)
![Bildschirmfoto 2021-05-10 um 11 11 15](https://user-images.githubusercontent.com/458603/117635936-9cd3f980-b180-11eb-92a1-dbbac187677a.png)

**Comment by zonky2** [comment]
Do you also get an error in the log for the URL:

https://www.alpenblick.at/de/anfragen?brilliant=3

**Comment by wschwaiger** [comment]
No, I don't get an error under var/logs/*

**Comment by e-spin** [comment]
fixed
